version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
    networks:
      - app-network

  backend:
    environment:
      - MONGO_URI = "mongodb+srv://nagonad:st081301003@pokemon.kvw0oiv.mongodb.net/"
      - PORT = 5000
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
